name: build-publish-sign-release
on:
  push:
    tags:
      - '*'
jobs:
  call-workflow-build-lint-test-cover-docs-upload:
    name: Call linting/testing workflow.
    uses: ./.github/workflows/build-lint-test-cover-docs-upload.yml
    secrets: inherit
  build:
    name: Build source distribution and bundle it with wheel files package.
    needs:
      - call-workflow-build-lint-test-cover-docs-upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Python.
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
          architecture: x64
      - name: Install pypa/build.
        run: python -m pip install .[publish]
      - name: Build a source tarball.
        run: python -m build --sdist .
      - name: Download all the binary wheels built during the prerequisite workflow.
        uses: actions/download-artifact@v5
        with:
          path: dist/
          merge-multiple: true
      - name: Store the package distributions in preparation for publishing.
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
  publish:
    name: Publish package to PyPI.
    if: startsWith(github.ref, 'refs/tags/') # Publish on tag pushes.
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/bcl
    permissions:
      id-token: write
    steps:
      - name: Ensure the package distributions directory is empty.
        run: rm -rf dist/*
      - name: Download all the package distributions.
        uses: actions/download-artifact@v5
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish package to PyPI.
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
  sign-release:
    name: Sign package distributions with Sigstore and upload them to a GitHub release.
    needs:
      - publish
    runs-on: ubuntu-latest
    permissions:
      contents: write # For GitHub.
      id-token: write # For Sigstore.
    steps:
      - name: Download all the package distributions.
        uses: actions/download-artifact@v5
        with:
          name: python-package-distributions
          path: dist/
      - name: Sign the package distributions with Sigstore.
        uses: sigstore/gh-action-sigstore-python@v3.0.1
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl
      - name: Create a GitHub release.
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release create '${{ github.ref_name }}' --repo '${{ github.repository }}'
      - name: Upload package distributions and signatures/certificates to the GitHub release.
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release upload
          '${{ github.ref_name }}' dist/**
          --repo '${{ github.repository }}'
