name: lint-test-cover-docs-build-upload
on:
  push
env:
  version: '2.3.1'
jobs:
  manylinux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    strategy:
      matrix:
        python:
          - {version: '3.7', version-abi: 'cp37', version-abi-suffix: 'cp37m'}
    name: 'Python ${{ matrix.python.version }} with ABI ${{ matrix.python.version-abi }} for manylinux2014_x86_64'
    steps:
      - uses: actions/checkout@v2
      - name: Install development dependencies.
        run: |
          yum -y install wget libffi-devel
      - name: Download libsodium source tree archive.
        run: |
          wget https://github.com/jedisct1/libsodium/releases/download/1.0.18-RELEASE/libsodium-1.0.18.tar.gz
          mv libsodium-1.0.18.tar.gz src/bcl/libsodium.tar.gz
      - name: Install Python.
        run: |
          /opt/python/${{ matrix.python.version-abi }}-${{ matrix.python.version-abi-suffix }}/bin/python -m pip install virtualenv
          /opt/python/${{ matrix.python.version-abi }}-${{ matrix.python.version-abi-suffix }}/bin/python -m virtualenv .venv
      - name: Install Python dependencies for build process.
        run: .venv/bin/pip install -U pip .[build]
