name: lint-test-cover-docs-build-upload
on:
  push
jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        windows:
          - {version: 'win32', arch: 'x86', arch-sodium: 'Win32', arch-vs: 'x86'}
        python:
          - {version: '3.10', version-abi: 'cp310'}
    name: Python ${{ matrix.python.version }} with ABI ${{ matrix.python.version-abi }} for Windows ${{ matrix.windows.arch }}
    env:
      WHEELNAME: bcl-${{ github.ref_name }}-${{ matrix.python.version-abi }}-abi3-${{ matrix.windows.version }}
      INCLUDE: C:\libsodium\include
      LIB: C:\libsodium\${{ matrix.windows.arch-sodium }}\Debug\v143\dynamic\
    steps:
      - uses: actions/checkout@v3
      - name: Download and extract libsodium dynamic library file.
        run: |
          wget -O c:\libsodium-1.0.18-msvc.zip https://download.libsodium.org/libsodium/releases/libsodium-1.0.18-stable-msvc.zip
          Expand-Archive c:\libsodium-1.0.18-msvc.zip -DestinationPath c:\
        shell: powershell
      - name: Install Python.
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python.version }}
          architecture: ${{ matrix.windows.arch }}
      - name: Install Python dependencies for build process.
        run: |
          python -m pip install -U pip .[build]
        shell: bash
      - name: Build wheel file.
        run: |
          mkdir wheelhouse
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -no_logo -arch=${{ matrix.windows.arch-vs }}
          python -m build --wheel
          mv dist/bcl*.whl wheelhouse
          cp build/lib*/bcl/_sodium.py src/bcl/_sodium.py
        shell: cmd
      - name: Test wheel installation.
        run: |
          pip install -f wheelhouse bcl --no-index --force-reinstall --no-dependencies
      - name: Lint and test module (and compiled libsodium shared library file).
        run: |
          python -m pip install -U pip .[lint,test]
          python -m pylint bcl src/bcl/_sodium.tmpl src/bcl/_sodium_build.py --disable=duplicate-code # Check against linting rules.
          python src/bcl/bcl.py -v # Run doctests.
          python -m pytest # Run tests.
      - name: Test auto-generation of documentation.
        run: |
          python -m pip install -U .[docs]
          cd docs
          sphinx-apidoc -f -E --templatedir=_templates -o _source .. ../src/bcl/_sodium_build.py
          make html
          cd ..
      - name: Upload wheel file.
        run: |
          mkdir bcl-wheelhouse
          move wheelhouse\bcl*.whl bcl-wheelhouse\${{ env.WHEELNAME }}.whl
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ env.WHEELNAME }}
          path: bcl-wheelhouse\
