name: lint-test-cover-docs-build-upload
on:
  push
env:
  version: '2.3.1'
jobs:
  manylinux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    strategy:
      matrix:
        python:
          - {version: '3.7', version-abi: 'cp37', version-abi-suffix: 'cp37m'}
    name: 'Python ${{ matrix.python.version }} with ABI ${{ matrix.python.version-abi }} for manylinux2014_x86_64'
    steps:
      - uses: actions/checkout@v2
      - name: Install development dependencies.
        run: |
          yum -y install wget libffi-devel
      - name: Download libsodium source tree archive.
        run: |
          wget https://github.com/jedisct1/libsodium/releases/download/1.0.18-RELEASE/libsodium-1.0.18.tar.gz
          mv libsodium-1.0.18.tar.gz src/bcl/libsodium.tar.gz
      - name: Install Python.
        run: |
          /opt/python/${{ matrix.python.version-abi }}-${{ matrix.python.version-abi-suffix }}/bin/python -m pip install virtualenv
          /opt/python/${{ matrix.python.version-abi }}-${{ matrix.python.version-abi-suffix }}/bin/python -m virtualenv .venv
      - name: Install Python dependencies for build process.
        run: .venv/bin/pip install -U pip .[build]
      - name: Build wheel file.
        run: |
          mkdir tmpwheelhouse
          LIBSODIUM_MAKE_ARGS="-j$(nproc)" .venv/bin/python -m build --wheel
          mv dist/bcl*.whl tmpwheelhouse
          mkdir wheelhouse
          mv tmpwheelhouse/bcl*.whl wheelhouse/
          cp build/lib*/bcl/_sodium.py src/bcl/_sodium.py
      - name: Test wheel installation.
        run: .venv/bin/pip install -f wheelhouse --no-index --force-reinstall --no-dependencies bcl
      - name: Lint and test module (and compiled libsodium shared library file).
        run: |
          .venv/bin/pip install -U .[lint,test]
          .venv/bin/python -m pylint bcl # Check against linting rules.
          .venv/bin/python src/bcl/bcl.py -v # Run doctests.
          .venv/bin/python -m pytest # Run tests.
      - name: Publish coverage results.
        run: |
          .venv/bin/pip install -U .[coveralls]
          .venv/bin/python -m coveralls --service=github # Submit to coveralls.
        if: matrix.python.version == '3.8'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test auto-generation of documentation.
        run: |
          .venv/bin/pip install -U .[docs]
          cd docs && ../.venv/bin/sphinx-apidoc -f -E --templatedir=_templates -o _source .. && cd ..
      - name: Upload wheel file.
        run: |
          mkdir bcl-wheelhouse
          mv wheelhouse/bcl*.whl bcl-wheelhouse/
      - uses: actions/upload-artifact@v1
        with:
          name: 'bcl-${{ env.version }}-${{ matrix.python.version-abi }}-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64'
          path: bcl-wheelhouse/
