name: lint-test-cover-docs-build-upload
on:
  push
jobs:
  macos-intel:
    runs-on: macos-15-intel
    strategy:
      matrix:
        python:
          - {version: '3.9', abi: 'cp39', url: '3.9.13'}
          - {version: '3.10', abi: 'cp310', url: '3.10.11'}
          - {version: '3.11', abi: 'cp311', url: '3.11.9'}
          - {version: '3.12', abi: 'cp312', url: '3.12.10'}
          - {version: '3.13', abi: 'cp313', url: '3.13.7'}
    name: Python ${{ matrix.python.version }} with ABI ${{ matrix.python.abi }} for macOS 11
    env:
      WHEELNAME: bcl-${{ github.ref_name }}-${{ matrix.python.abi }}-abi3-macos11
    steps:
      - uses: actions/checkout@v5
      - name: Install Python.
        run: |
          curl "https://www.python.org/ftp/python/${{ matrix.python.url }}/python-${{ matrix.python.url }}-macos11.pkg" -o python.pkg
          sudo installer -pkg python.pkg -target /
          /Library/Frameworks/Python.framework/Versions/${{ matrix.python.version }}/bin/python3 -m pip install -U virtualenv
          /Library/Frameworks/Python.framework/Versions/${{ matrix.python.version }}/bin/python3 -m virtualenv venv
      - name: Download libsodium source tree archive.
        run: |
          wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.18.tar.gz
          mv libsodium-1.0.18.tar.gz src/bcl/libsodium.tar.gz
      - name: Install Python dependencies for build process.
        run: |
          venv/bin/pip install -U pip .[build]
      - name: Build wheel file.
        run: |
          mkdir wheelhouse
          rm -f dist/*.*
          LIBSODIUM_MAKE_ARGS="-j$(sysctl -n hw.ncpu)" \
              venv/bin/python -m build --wheel && mv dist/bcl*.whl wheelhouse
          cp build/lib*/bcl/_sodium.py src/bcl/_sodium.py
      - name: Test wheel installation.
        run: |
          venv/bin/pip install -f wheelhouse --no-index --force-reinstall --no-dependencies bcl
      - name: Lint and test module (and compiled libsodium shared library file).
        run: |
          venv/bin/pip install -U pip .[lint,test]
          venv/bin/python -m pylint bcl src/bcl/_sodium.tmpl src/bcl/_sodium_build.py --disable=duplicate-code # Check against linting rules.
          venv/bin/python src/bcl/bcl.py -v # Run doctests.
          venv/bin/python -m pytest # Run tests.
      - name: Test auto-generation of documentation.
        run: |
          venv/bin/pip install -U .[docs]
          cd docs
          ../venv/bin/sphinx-apidoc -f -E --templatedir=_templates -o _source .. ../src/bcl/_sodium_build.py
          make html SPHINXBUILD='../venv/bin/sphinx-build'
          cd ..
      - name: Upload wheel file.
        run: |
          mkdir bcl-wheelhouse
          mv wheelhouse/bcl*.whl bcl-wheelhouse/${{ env.WHEELNAME }}.whl
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.WHEELNAME }}
          path: bcl-wheelhouse/
